Ray worker pid: 41048
/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/numpy/core/fromnumeric.py:3118: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/ray/workers/default_worker.py", line 98, in <module>
    ray.worker.global_worker.main_loop()
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/ray/worker.py", line 1052, in main_loop
    self._wait_for_and_process_task(task)
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/ray/worker.py", line 1003, in _wait_for_and_process_task
    self._process_task(task, execution_info)
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/ray/worker.py", line 908, in _process_task
    self.actors[key], *arguments)
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/ray/function_manager.py", line 792, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/beast/srikar/apex/rl/algos/td3.py", line 139, in collect_experience
    self.learner_id.get_global_policy.remote())
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/ray/worker.py", line 2191, in get
    values = worker.get_object(object_ids)
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/ray/worker.py", line 546, in get_object
    int(0.01 * len(unready_ids)),
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/ray/worker.py", line 424, in retrieve_and_deserialize
    with_meta=True,
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/ray/utils.py", line 480, in _wrapper
    return orig_attr(*args, **kwargs)
  File "pyarrow/_plasma.pyx", line 390, in pyarrow._plasma.PlasmaClient.get_buffers
  File "pyarrow/_plasma.pyx", line 286, in pyarrow._plasma.PlasmaClient._get_object_buffers
  File "pyarrow/error.pxi", line 83, in pyarrow.lib.check_status
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/ray/pyarrow_files/pyarrow/compat.py", line 115, in frombytes
    def frombytes(o):
KeyboardInterrupt
